# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a75f251388dedeff22827f66c39410c4d91afa0c9ae3e202c95fef44a02742cf2155f01c950f076f1088ec988961f8e1cb766e2b1566356f962d7a29e82e6bd

test:
  secret_key_base: 5780c54a739cb3e9f93fc374a561a6ea00ddaf889d38395c063bbc29dabfa84fc75098bf37715ec1a2b0ca0d316fc4aa3a9c03ace2f3ee234d938b790023665f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
